/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfitsRouteImport } from './routes/profits'
import { Route as PerformanceRouteImport } from './routes/performance'

const ProfitsRoute = ProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/performance': typeof PerformanceRoute
  '/profits': typeof ProfitsRoute
}
export interface FileRoutesByTo {
  '/performance': typeof PerformanceRoute
  '/profits': typeof ProfitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/performance': typeof PerformanceRoute
  '/profits': typeof ProfitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/performance' | '/profits'
  fileRoutesByTo: FileRoutesByTo
  to: '/performance' | '/profits'
  id: '__root__' | '/performance' | '/profits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PerformanceRoute: typeof PerformanceRoute
  ProfitsRoute: typeof ProfitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profits': {
      id: '/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof ProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PerformanceRoute: PerformanceRoute,
  ProfitsRoute: ProfitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
