/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfitsRouteImport } from './routes/profits'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as CarteiraProfitsRouteImport } from './routes/carteira-profits'
import { Route as IndexRouteImport } from './routes/index'

const ProfitsRoute = ProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraProfitsRoute = CarteiraProfitsRouteImport.update({
  id: '/carteira-profits',
  path: '/carteira-profits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira-profits': typeof CarteiraProfitsRoute
  '/performance': typeof PerformanceRoute
  '/profits': typeof ProfitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira-profits': typeof CarteiraProfitsRoute
  '/performance': typeof PerformanceRoute
  '/profits': typeof ProfitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira-profits': typeof CarteiraProfitsRoute
  '/performance': typeof PerformanceRoute
  '/profits': typeof ProfitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carteira-profits' | '/performance' | '/profits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carteira-profits' | '/performance' | '/profits'
  id: '__root__' | '/' | '/carteira-profits' | '/performance' | '/profits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraProfitsRoute: typeof CarteiraProfitsRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfitsRoute: typeof ProfitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profits': {
      id: '/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof ProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira-profits': {
      id: '/carteira-profits'
      path: '/carteira-profits'
      fullPath: '/carteira-profits'
      preLoaderRoute: typeof CarteiraProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraProfitsRoute: CarteiraProfitsRoute,
  PerformanceRoute: PerformanceRoute,
  ProfitsRoute: ProfitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
